apiVersion: v1
kind: Service
metadata:
  name: ss-api-svc
  annotations:
    dev.okteto.com/auto-ingress: "3-webshot-api.tuna2134.dev"
spec:
  selector:
    app: ss-api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
