apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ss-api
  template:
    metadata:
      labels:
        app: ss-api
    spec:
      containers:
      - name: ss-api
        image: ghcr.io/mc-fdc-dev/screenshot-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: KUBERNETES_MODE
          value: "true"
        resources:
          requests:
            memory: 0.1Gi
            cpu: 50Mi
