apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium-deployment
  labels:
    app: chromium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromium
  template:
    metadata:
      labels:
        app: chromium
    spec:
      containers:
      - name: chromium
        image: ghcr.io/tuna2134/chromium-docker:latest
        ports:
        - containerPort: 9222
        args:
        - "--headless"
        - "--disable-gpu"
        - "--remote-debugging-address=0.0.0.0"
        - "--remote-debugging-port=9222"
        - "--no-sandbox"
        - "--allowed-origins=*"
        - "--proxy-server=http://proxy1.d1.rspsrv.jp:26020"
        - "--ignore-certificate-errors"
        - "--ignore-certificate-errors-spki-list"
        - "--hide-scrollbars"
        - "--disable-dev-shm-usage"
        - "--no-first-run"
        resources:
          limits:
            memory: 0.5Gi
          requests:
            memory: 0.1Gi
