version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspaces:cached
    networks:
      basic:

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    environment:
      BROWSER_ADDRESS: browser
      BROWSER_PORT: "9222"
  
  browser:
    image: ghcr.io/mc-fdc-dev/chromium-docker
    args:
    - "--headless"
    - "--disable-gpu"
    - "--remote-debugging-address=0.0.0.0"
    - "--remote-debugging-port=9222"
    - "--no-sandbox"
    - "--proxy-server=http://proxy1.d1.rspsrv.jp:26020"
    - "--ignore-certificate-errors"
    - "--ignore-certificate-errors-spki-list"
    - "--hide-scrollbars"
    - "--disable-dev-shm-usage"
    - "--no-first-run"
    networks:
      basic:

networks:
  basic: